name: sagaforge
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.10.5=h4c7d964_0
  - click=8.3.0=pyh7428d3b_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - liblzma=5.8.1=h2466b09_2
  - libmpdec=4.0.0=h2466b09_0
  - libsqlite=3.50.4=hf5d6505_0
  - libzlib=1.3.1=h2466b09_2
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - openssl=3.5.4=h725018a_0
  - pip=25.2=pyh145f28c_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.13.9=h09917c8_101_cp313
  - python_abi=3.13=8_cp313
  - rich=14.2.0=pyhcf101f3_0
  - tk=8.6.13=h2c6b04d_2
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - pip:
      - agno==2.0.10
      - annotated-types==0.7.0
      - anyio==4.11.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.4
      - dnspython==2.8.0
      - docstring-parser==0.17.0
      - email-validator==2.3.0
      - fastapi==0.117.1
      - fastapi-cli==0.0.13
      - fastapi-cloud-cli==0.2.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - greenlet==3.2.4
      - h11==0.16.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - idna==3.10
      - jinja2==3.1.6
      - logging==0.4.9.6
      - markupsafe==3.0.2
      - ollama==0.6.0
      - packaging==25.0
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydantic-settings==2.11.0
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - pyyaml==6.0.3
      - regex==2025.9.18
      - requests==2.32.5
      - rich-toolkit==0.15.1
      - rignore==0.6.4
      - sentry-sdk==2.39.0
      - shellingham==1.5.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - sqlalchemy==2.0.43
      - sqlmodel==0.0.25
      - starlette==0.48.0
      - tavily-python==0.7.12
      - tiktoken==0.12.0
      - typer==0.19.2
      - typing-inspection==0.4.1
      - urllib3==2.5.0
      - uvicorn==0.37.0
      - watchfiles==1.1.0
      - websockets==15.0.1
prefix: C:\Users\John\miniconda3\envs\sagaforge
